# Generated by Django 4.2.1 on 2023-05-21 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 13, 48, 8, 401082, tzinfo=datetime.timezone.utc)),
        ),
    ]
